name: Lint

on:
  push:
    branches: [ develop ]
    paths:
      - '**.php'
  pull_request:
    branches: [ develop ]
    paths:
      - '**.php'
  workflow_dispatch:

env:
  php-version: '7.4'

jobs:

  phpcs:

    name: 'Coding Standards with PHP CodeSniffer'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          tools: composer, cs2pr
          coverage: none
        env:
          fail-fast: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: Auto fix coding standards
        run: composer phpcs-fix
        continue-on-error: true

      - name: Commit coding standards fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix coding standards with phpcbf

      - name: Check coding standards
        run: composer phpcs -- -q -n --report=checkstyle | cs2pr

  php-lint:

    name: 'Syntax with PHP Parallel Lint'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          tools: composer, cs2pr
          coverage: none
        env:
          fail-fast: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: Check syntax
        run: composer php-lint

  phpstan:

    name: 'Static Analysis with PHPStan'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          tools: composer, cs2pr
          coverage: none
        env:
          fail-fast: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: Static Analysis
        id: phpstan
        run: composer phpstan -- --error-format=github

      - name: Update basefile
        run: composer phpstan-baseline

      - name: Commit updated basefile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update PHPStan basefile

  phpmd:

    name: 'Mess Detection with PHPMD'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          tools: composer, cs2pr
          coverage: none
        env:
          fail-fast: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: Detect mess
        run: composer phpmd-ga

      - name: Update basefile
        run: composer phpmd-baseline

      - name: Commit updated basefile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update PHPMD basefile
